# Домашнее задание №5

### Задание №1 (1,5 балла)

Создайте два массива: в первом должны быть четные числа от 2 до 12 включительно, а в другом числа 7, 11, 15, 18, 23, 29.

In [4]:
import numpy as np

In [5]:
A = np.array([2, 4, 6, 8, 10, 12])
B = np.array([7, 11, 15, 18, 23, 29])
A

array([ 2,  4,  6,  8, 10, 12])

$1.$ Сложите массивы и возведите элементы получившегося массива в квадрат:

In [6]:
(A+B)**2

array([  81,  225,  441,  676, 1089, 1681], dtype=int32)

$2.$ Выведите все элементы из первого массива, которые стоят на тех местах, где элементы второго массива больше 12 и дают остаток 3 при делении на 5.

In [7]:
B[B>12]
A[np.arange(B.shape[0])%5==3]

array([8])

*3.* Для первого массива найдите остатки от деления на 2, а для второго --- на 3. Для каждого получившегося массива выведите его уникальные значения (см. семинар).

In [8]:
np.unique(A%2)

array([0], dtype=int32)

In [9]:
np.unique(B%3)

array([0, 1, 2], dtype=int32)

### Задание №2 (1,5 балла)

Найдите интересный для вас датасет. Например, можно выбрать датасет [тут](http://data.un.org/Explorer.aspx) или [тут](https://hls.harvard.edu/library/research/find-a-database/). Если выскакивают ошибки при считывании таблицы, попробуйте их погуглить и решить проблему!

1. Рассчитайте подходящие описательные статистики для признаков объектов в выбранном датасете
2. Проанализируйте и прокомментируйте содержательно получившиеся результаты
    - недостаточно написать фразы формата "Средний возраст = 60, а минимальный = 20", следует дать пояснение, что это значит и какие выводы можно сделать в рамках датасета
3. Все комментарии оформляйте строго в ячейках формата Markdown
    - для этого надо в выпадающем окошке сверху для текущей ячейки сменить тип Code на Markdown
    ![](https://i.imgur.com/vl7Fmg9.png)

In [14]:
dataset = np.loadtxt("untitled.txt", dtype=int)

In [15]:
dataset

array([[ 2001, 20023,   200,    12],
       [ 2002, 50002,   122,    32],
       [ 2003, 12222,   319,    12],
       [ 2004, 23111,   244,    55],
       [ 2005, 50002,   244,    11],
       [ 2006, 12000,   315,    65],
       [ 2007, 15550,   111,    14],
       [ 2008, 12222,   122,    22],
       [ 2009, 19004,   999,    55]])

#### Среднее значение:

In [18]:
np.mean(dataset[:, 1])

23792.88888888889

#### Медиана:

In [19]:
np.median(dataset[:, 2])

244.0

#### Размах:

In [20]:
np.max(dataset[:, 0])-np.min(dataset[:, 0])

8

#### Дисперсия:

In [22]:
np.var(dataset[:, 3])

422.32098765432096