# Семинар по numpy

В этом семинаре мы познакомимся с первой библиотекой, которая понадобится нам в курсе - библиотекой numpy. Это библиотека для работы с матрицами, и она может быть также полезна для матричных вычислений в других дисциплинах. Но сначала познакомимся с интерфейсом jupyter notebook. Это инструмент, позволяющий писать код в интерактивном режиме, рисовать графики и оформлять материалы.

## Очень краткий обзор интерфейса jupyter notebook
Jupyter notebook состоит из ячеек.
В ячейку можно записывать код, выполнять, а потом использовать созданные переменные / определенные функции и т. д. в других ячейках:

In [63]:
x = [1, 2, 3]

In [64]:
print(x)

[1, 2, 3]


In [65]:
x = 9

In [66]:
y = 3

Выполнить ячейку: shift + enter, показать аргументы функции: shift + tab. Есть много других горячих клавиш, см. Help -> Keyboard Shortcuts (вверху интерфейса). Там же есть Help -> User Interface Tool!

Обратите внимание на кнопки + (добавить ячейку), ножницы (удалить ячейку), стрелки, меняющие ячейки местами, кнопку остановить выполнение.

Ноутбук сохраняется автоматически. Чтобы скачать: File -> Download as -> ipynb.

Этот текст написан в ячейке типа Markdown, она позволяет красиво оформлять код. Переключение типа ячейки справа от кнопки стоп (черный квадрат). Ячейки с кодом имеют тип Code.

## Создание массивов в numpy

Numpy - библиотека для работы с матрицами. Импортируем библиотеку:

In [67]:
import numpy as np

Предположим, что мы провели опрос, в котором было четыре вопроса, на каждый можно ответить Да, Нет, Воздержался. В итоге получим таблицу размера 4 на 3. Создадим такую таблицу в numpy:

In [68]:
l = [[30, 2, 0], [3, 27, 1], [28, 1, 1], [6, 17, 5]]
ar = np.array(l)

In [69]:
ar # выводится созданное в последней строке, если в ней нет присваивания (знак =)

array([[30,  2,  0],
       [ 3, 27,  1],
       [28,  1,  1],
       [ 6, 17,  5]])

Можно создавать массивы из нулей (np.zeros) или из единиц (np.ones):

In [70]:
A = np.ones((7, 9))
A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Также часто используется создание векторов из натуральных чисел:

In [71]:
vec = np.arange(15)
vec

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

И случайно сгенерированные массивы:

In [72]:
r = np.random.rand(3, 5)
r

array([[0.01016923, 0.16293781, 0.58152999, 0.7950335 , 0.42245828],
       [0.66550271, 0.3868643 , 0.97428794, 0.84110118, 0.80909695],
       [0.62269575, 0.50861566, 0.50549434, 0.24339984, 0.89562332]])

### Размерности массивов

Размерности:

In [73]:
ar.shape[0]

4

In [74]:
A.shape

(7, 9)

In [75]:
vec.shape

(15,)

В numpy нулевая размерность отвечает за строки, первая - за столбцы. В нашей матрице ar 4 строки и 3 столбца. Вообще в numpy можно создавать массивы любых размерностей точно таким же образом, как мы сделали выше - numpy не различает векторы, матрицы и тензоры, все они называются массивами. Например, vec имеет длину 15 только по одной размерности, поэтому его shape равен (15,). Shape - это обычный кортеж языка python.

Можно вытянуть все ответы в одну строку:

In [76]:
ar.ravel()

array([30,  2,  0,  3, 27,  1, 28,  1,  1,  6, 17,  5])

Можно наоборот: преобразовать вектор в матрицу:

In [77]:
vec.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Обратите внимание, что числа записываются по строкам.

In [78]:
vec.reshape(3, 5).shape

(3, 5)

По одной из осей можно указывать -1, тогда библиотека сама посчитает число элементов по этой размерности:

In [79]:
vec.reshape(3, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Аналогичным образом можно дублироать функционал функции ravel:

In [80]:
vec.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Операции с массивами

Можно выделить три группы операций с массивами в numpy:
* поэлементные
* матричные
* агрегирующие

Поэлементные выполняются между массивами одной формы (shape), хотя ниже мы обсудим некое обощение правила одной формы.

In [81]:
vec + vec + vec

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42])

In [82]:
A * 10

array([[10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [83]:
x = np.array([1, 2, 3])
y = np.array([-1, 1, -1])
x * y

array([-1,  2, -3])

Обратите внимание, что * - это поэлементное умножение, а не матричное!

In [84]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

Матричные операции - операции из линейной алгебры. Например, матричное произведение:

In [85]:
A = np.random.rand(7, 8)
B = np.random.rand(8, 3)
A.dot(B)

array([[1.69928693, 2.01301798, 1.7829779 ],
       [2.98383448, 3.17366772, 3.13129435],
       [2.32403007, 2.811146  , 2.57275267],
       [2.57119801, 2.54665007, 2.46508769],
       [1.56768699, 2.55819943, 2.00957211],
       [1.90778141, 2.59032822, 2.20481539],
       [2.5550347 , 3.24758813, 3.09551075]])

Можно писать и так:

In [86]:
np.dot(A, B)

array([[1.69928693, 2.01301798, 1.7829779 ],
       [2.98383448, 3.17366772, 3.13129435],
       [2.32403007, 2.811146  , 2.57275267],
       [2.57119801, 2.54665007, 2.46508769],
       [1.56768699, 2.55819943, 2.00957211],
       [1.90778141, 2.59032822, 2.20481539],
       [2.5550347 , 3.24758813, 3.09551075]])

И так:

In [87]:
A @ B

array([[1.69928693, 2.01301798, 1.7829779 ],
       [2.98383448, 3.17366772, 3.13129435],
       [2.32403007, 2.811146  , 2.57275267],
       [2.57119801, 2.54665007, 2.46508769],
       [1.56768699, 2.55819943, 2.00957211],
       [1.90778141, 2.59032822, 2.20481539],
       [2.5550347 , 3.24758813, 3.09551075]])

Проверим форму:

In [88]:
A.dot(B).shape

(7, 3)

Обращение матрицы:

In [89]:
np.linalg.inv(np.random.rand(3, 3))

array([[-1.17730946,  2.19517176, -0.72861201],
       [ 2.11092126, -0.62192027, -0.65542786],
       [-0.27564745, -0.49640629,  3.10278403]])

Модуль np.linalg содержит много полезных матричных функций, их можно посмотреть в документации модуля.

 Агрегирующие операции агрерируют информацию в троках, столбцах, во всем массиве и т. д. Самые популярные такие операции - суммирование np.sum, усреднение np.mean, медиана np.median, максимум np.max и минимум np.min.

Число полученных ответов на вопросы (всего): 

In [90]:
np.sum(ar)

121

Пробуем выяснить число респондентов. Для этого просуммируем матрицу по строкам (это делается с помощью указания axis=1):

In [91]:
np.sum(ar, axis = 1) 

array([32, 31, 30, 28])

In [92]:
np.sum(ar, axis = 1).shape

(4,)

По столбцам: axis=0, по строкам: axis=1.

В результате суммирования получился вектор (размерность на 1 меньше, чем у исходной матрицы). Можно указать keepdims=True, чтобы сохранть размерности:

In [93]:
np.sum(ar, axis = 1, keepdims=True).shape

(4, 1)

Задание для студентов: посчитать сумму по строкам, используя матричное произведение.

In [94]:
np.sum(A.dot(B), axis=1)

array([5.49528282, 9.28879654, 7.70792874, 7.58293577, 6.13545853,
       6.70292501, 8.89813358])

Считаем число ответов "да", "нет", "воздержался" двумя способами:

In [95]:
np.sum(ar, axis=0)

array([67, 47,  7])

In [96]:
ones = np.ones(4)

In [97]:
np.dot(ones, ar)

array([67., 47.,  7.])

### Индексация
Для индексации ставим [ ] и через запятую перечисляем действия с осями. В матрице 0 - по вертикали, 1 - по горизонтали

In [98]:
ar[1, 1] # выбрать 1 элемент

27

In [99]:
ar # вывели для проверки

array([[30,  2,  0],
       [ 3, 27,  1],
       [28,  1,  1],
       [ 6, 17,  5]])

In [100]:
ar[:, 2] # выделить столбец

array([0, 1, 1, 5])

In [101]:
ar[:, -1] # выделить последний столбец

array([0, 1, 1, 5])

In [102]:
ar[0] # выделить строку

array([30,  2,  0])

In [103]:
ar[:, ::2] # выделить все столбы с четными номерами

array([[30,  0],
       [ 3,  1],
       [28,  1],
       [ 6,  5]])

 Можно делать логическую индексацию, чтобы выбирались только те элементы, для которых стоит True. Выберем ответы на вопросы с номерами, кратными 2: 

In [104]:
 ar[np.arange(ar.shape[0])%2==0]

array([[30,  2,  0],
       [28,  1,  1]])

### Добавление оси

Для удобного перехода между размерностями используют добавление оси. Вектор можно сделать матрицей с размером 1 по одной из размерностей.

In [105]:
ones[:, np.newaxis]

array([[1.],
       [1.],
       [1.],
       [1.]])

In [106]:
ones[:, np.newaxis].shape 
# вместо вектора с формой (4,) стала матрциа с формой (4, 1)

(4, 1)

In [107]:
ones[np.newaxis, :]
# вместо вектора с формой (4,) стала матрциа с формой (1, 4)

array([[1., 1., 1., 1.]])

In [108]:
ones[np.newaxis, :].shape

(1, 4)

### Добавление оси в поэлементных операциях

В поэлементных операциях можно использовать не только массивы в одинаковым в точности размером. В общем виде условие такое: по каждой размерности либо размер совпадает, либо в одном из массивов размер 1. Например, матрица размера (4, 3) и вектор размера (4, 1). В этом случае при выполнении операции столбец будет как бы "дублироваться" для каждого столбца в первой матрице. Воспользуемся этим, чтобы найти долю каждого ответа на все вопросы:

In [109]:
sums = ar.sum(axis=1) # всего ответов на каждый вопрос
sums.shape

(4,)

In [110]:
sums[:, np.newaxis].shape # добавили ось

(4, 1)

In [111]:
ar / sums[:, np.newaxis] # поделили число каждого варианта на общее число ответов на вопрос

array([[0.9375    , 0.0625    , 0.        ],
       [0.09677419, 0.87096774, 0.03225806],
       [0.93333333, 0.03333333, 0.03333333],
       [0.21428571, 0.60714286, 0.17857143]])

### Объединение массивов

Добавляем новый вопрос в таблицу:

In [112]:
row = np.array([5, 12, 15])
row = row[np.newaxis, :] 
# конкретно тут можно без увеличения размерности
# но в других случаях может быть ошибка, лучше добавлять
ar = np.vstack((ar, row))

Добавляем новый столбец в таблицу - максимальное число ответов:

In [113]:
mx = np.max(ar, 1)
mx

array([30, 27, 28, 17, 15])

In [114]:
mx.shape

(5,)

In [115]:
mx = mx[:, np.newaxis]

In [116]:
ar = np.hstack ((ar, mx))
ar

array([[30,  2,  0, 30],
       [ 3, 27,  1, 27],
       [28,  1,  1, 28],
       [ 6, 17,  5, 17],
       [ 5, 12, 15, 15]])

Удаление строки (аналогично можно удалять столбец):

In [117]:
np.delete(ar, np.arange(3, 4), axis=1)

array([[30,  2,  0],
       [ 3, 27,  1],
       [28,  1,  1],
       [ 6, 17,  5],
       [ 5, 12, 15]])

### Задания для студентов

Выделите строки, у которых ответов "нет" больше, чем ответов "да":

In [118]:
ar[ar[:, 0]<ar[:, 1]] 

array([[ 3, 27,  1, 27],
       [ 6, 17,  5, 17],
       [ 5, 12, 15, 15]])

Вывести квадраты первых десяти натуральных чисел:

In [119]:
np.arange(10)**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

Перемешать числа натуральные числа от 1 до 10 (воспользуйтесь np.random.permutation):

In [120]:
np.random.permutation(10)

array([5, 7, 4, 0, 9, 8, 6, 3, 1, 2])

In [121]:
# student's code here


Составить таблицу умножения от 1 до 10:

In [122]:
p = np.arange(1, 10)
p * p[:, None]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])